---
:live:
  :tmpdir: /tmp/
  :cachedir: /var/cache/live
  :title: Foreman Metal
  :product: Metal
  :fslabel: foreman-metal
  :compression: gzip
  :releasever: 6
:ipxe:
  :baseurl: http://192.168.69.10/static/foreman/metal/tftpboot/
  :initrd: initrd0.img
  :vmlinuz: vmlinuz0
